app:
  jwtSecret: ${JWT_SECRET_KEY}
  jwtExpirationMs: 600000
  dataLoader: true

server:
  port: 8080
#logging:
#    level:
#        root: debug
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
